### ISSUE TITLE
no license file or cargo.toml license field is present

### ISSUE THREAD

**Issue by Lokathor** [connorskees/simd-png#1]
please add a license of some sort so that we can use these great findings of yours.

If you don't have any preference of your own, might I suggest `Zlib OR Apache-2.0 OR MIT`.

**Comment by connorskees** [comment]
Hello,

Thank you for your interest in this project. I have added an MIT license in https://github.com/connorskees/simd-png/commit/7300436da490cd4424e1633197f61b537cf365b2.
